#!/bin/bash

add-ssh-config:
	@/bin/bash "/shell-tools/ask_ssh_config.sh"

add-pub-key:
	@/bin/bash "/shell-tools/add_pub_key_to_remote.sh"

get-db:
	@/bin/bash "/shell-tools/get_db.sh"

import-db:
	@/bin/bash "/shell-tools/import.sh"
