#!/usr/bin/env bash

platform::command_exists() {
  type "$1" &>/dev/null
}

platform::is_macos() {
  [[ $(uname -s) == "Darwin" ]]
}

platform::is_linux() {
  [[ $(uname -s) == "Linux" ]]
}

platform::is_arm() {
  [[ $(arch) == "arm64" ]]
}

build_and_log() {
  local build_dir="$1"
  local log_dir="$2"
  make -C "$build_dir" image-build --no-print-directory |
    tee "$log_dir"
}

build_and_log_arm(){
  local build_dir="$1"
  local log_dir="$2"
  make -C "$build_dir" image-build-arm --no-print-directory |
    tee "$log_dir"
}

replace_string_in_file(){
  local file_path=$1
  local search=$2
  local replace=$3
  sed "s@$search@$replace@" "$file_path" |
  tee "$file_path.tmp" >/dev/null
  mv "$file_path.tmp" "$file_path"
}

sleep_and_countdown(){
  echo "in 3..."
  sleep 3
  echo "in 2..."
  sleep 2
  echo "in 1..."
  sleep 1
}
