#!/usr/bin/env bash

if ! command -v brew; then
  echo "⚡️ Installing brew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
  echo "⚡️ Updating brew"
  brew update
fi
