#!/usr/bin/env bash

repo_root=$1

container_id=$(docker ps --format '{{.ID}} {{.Names}}' | fzf --reverse --height=50% | awk '{print $1}')
if [ -n "$container_id" ]; then
  docker exec -it "$container_id" bash
fi
