#!/usr/bin/env bash

repo_root=$1

if [ -z "$repo_root" ]; then
    echo "enter the root of this repo"
    exit 1
fi

if [ ! -d "$repo_root" ]; then
    echo "not a directory"
    exit 1
fi


make -C "$repo_root/reverse-proxy-apache" run --no-print-directory
make -C "$repo_root/mailhog" run --no-print-directory
/bin/bash "$repo_root/shell-tools/env/add_host_without_read" "portainer.local.com"
/bin/bash "$repo_root/shell-tools/env/add_host_without_read" "mailhog.local.com"
